language: ruby
sudo: required
rvm:
- 2.3.3

before_install:
  - sudo update-ca-certificates

before_script:
 - chmod +x ./travis/test # or do this locally and commit
 - chmod +x ./travis/deploy

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - ./travis/test

# branch whitelist, only for GitHub Pages
branches:
  only:
  - develop
  - master

after_success:
  - ./travis/deploy

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
