# top level stuff you probably don't need to touch
#highlighter: pygments
#markdown: rdiscount
markdown: kramdown
highlighter: rouge
#rdiscount:
#  extensions: [smart]
paginate: 5
paginate_path: "/:num/"
#paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
port: 3000
permalink: pretty
#safe: true

exclude:
  - CNAME
  - Gemfile*
  - README.md
  - LICENSE
  - _posts/examples
  - vendor


# edit here to achieve your personal greatness
#url: "https://alexsalom.es"
#baseurl: ""
avatar: profile.jpg
image: /static/img/profile.jpg
github: asalom # username
linkedin: alexsalom
stackoverflow: users/1266056/alex-salom   
google_analytics: UA-42771965-1
title: Alex Salom, Freelance iOS Developer
author: Alex Salom
description: This is the personal site of Alex Salom, a Freelance iOS Developer with a background in Software Engineering.
twitter:
  username: empatiia
logo: /static/img/profile.jpg

# needed for travis-ci build
#exclude: [vendor]
