[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.159.0"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/about/"
  to = "/me/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/me/"
  status = 301
